Repository monstar-lab-oss/nestjs-starter-rest-api, pull requests merged in 2020-12, with the labels that each got.

#52 Auth Module - Minor refactor
  src/auth/auth.module.ts
  src/auth/constants/strategy.constant.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/guards/jwt-refresh.guard.ts
  src/auth/guards/local-auth.guard.ts
  src/auth/strategies/jwt-auth.strategy.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/local.strategy.ts
Labels: enhancement

#54 Add RBAC authorization
  migrations/1607946140933-RefactorUserTable.ts
  src/auth/constants/role.constant.ts
  src/auth/controllers/auth.controller.spec.ts
  src/auth/controllers/auth.controller.ts
  src/auth/decorators/role.decorator.ts
  src/auth/dtos/auth-register-input.dto.ts
  src/auth/dtos/auth-register-output.dto.ts
  src/auth/dtos/auth-token-output.dto.ts
  src/auth/guards/roles.guard.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
  src/auth/strategies/jwt-auth.strategy.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/main.ts
  src/shared/dtos/pagination-params.dto.ts
  src/user/controllers/user.controller.ts
  src/user/dtos/user-create-input.dto.ts
  src/user/dtos/user-output.dto.ts
  src/user/entities/user.entity.ts
  src/user/services/user.service.spec.ts
  test/auth/auth.e2e-spec.ts
  test/user/user.e2e-spec.ts
Labels: enhancement

#58 Add isAccountDisabled field to user - Part 1/2
  migrations/1608194453705-RefactorUserTable.ts
  migrations/1608194504651-RefactorUserTable.ts
  src/auth/controllers/auth.controller.spec.ts
  src/auth/dtos/auth-register-input.dto.ts
  src/auth/dtos/auth-register-output.dto.ts
  src/auth/services/auth.service.spec.ts
  src/cli.ts
  src/user/controllers/user.controller.spec.ts
  src/user/dtos/user-create-input.dto.ts
  src/user/dtos/user-output.dto.ts
  src/user/entities/user.entity.ts
  src/user/repositories/user.repository.spec.ts
  src/user/services/user.service.spec.ts
  test/auth/auth.e2e-spec.ts
  test/user/user.e2e-spec.ts
Labels: :pray: Please Review Me, enhancement

#66 feat: added example values in env template
  .env.template
Labels: :technologist: Hackathon 2020

#61 fix: update docker run command in readme
  README.md
Labels: :technologist: Hackathon 2020, documentation

#69 Feat/add contributing md
  CONTRIBUTING.md
Labels: :technologist: Hackathon 2020, documentation

#67 feat: admin user create for e2e tests
  test/auth/auth.e2e-spec.ts
  test/test-utils.ts
  test/user/user.e2e-spec.ts
Labels: :technologist: Hackathon 2020

#68 feat: prevent disabled user account from logging in
  src/auth/dtos/auth-register-input.dto.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
  test/auth/auth.e2e-spec.ts
Labels: :technologist: Hackathon 2020

#72 feat: update README - Minor change
  README.md
Labels: documentation
