Repository monstar-lab-oss/nestjs-starter-rest-api, pull requests merged in 2020-08, with the labels that each got.

#7 feat: docker compose
  .gitignore
  README.md
  docker-compose.yml
Labels: enhancement

#8 all exception handler
  src/shared/filter/all-exceptions.filter.spec.ts
  src/shared/filter/all-exceptions.filter.ts
  src/shared/shared.module.ts
Labels: enhancement

#12 Add nestjs-pino package and sample implementation.
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.service.ts
  src/main.ts
  src/shared/filter/all-exceptions.filter.spec.ts
  src/shared/filter/all-exceptions.filter.ts
  src/shared/interceptor/logging.interceptor.spec.ts
  src/shared/interceptor/logging.interceptor.ts
  src/shared/logger/logger.module.ts
  src/shared/logger/logger.service.spec.ts
  src/shared/logger/logger.service.ts
  src/shared/shared.module.ts
  test/app.e2e-spec.ts
Labels: enhancement

#13 Add logger service.
  docker-compose.yml
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.service.ts
  src/main.ts
  src/shared/filter/all-exceptions.filter.spec.ts
  src/shared/filter/all-exceptions.filter.ts
  src/shared/logger/logger.module.ts
  src/shared/logger/logger.service.spec.ts
  src/shared/logger/logger.service.ts
Labels: enhancement

#11 JWT auth and User module
  .dockerignore
  .env.template
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  migrations/1597822219037-CreateUsers.ts
  ormconfig.js
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/register.dto.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/shared/config/configuration.ts
  src/shared/config/module-options.ts
  src/shared/shared.module.ts
  src/user/dto/add-user.dto.ts
  src/user/dto/me.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: enhancement

#24 Revert to stable swagger version
  package-lock.json
  package.json
  src/main.ts
Labels: bug

#9 unit test for all exception filter
  src/shared/filter/all-exceptions.filter.spec.ts
  src/shared/filter/all-exceptions.filter.ts
Labels: enhancement

#25 Update README and import paths for test
  README.md
  package-lock.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/shared/filter/all-exceptions.filter.spec.ts
  src/user/user.module.ts
Labels: documentation

#26 Auth validation
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/register.dto.ts
  src/main.ts
  src/shared/config/configuration.ts
  src/shared/config/module-options.ts
Labels: enhancement

#28 Minor updates on README
  .env.template
  README.md
  docker-compose.yml
  ormconfig.js
  src/auth/auth.module.ts
  src/shared/config/configuration.ts
  src/shared/config/module-options.ts
Labels: documentation
