Repository monstar-lab-oss/nestjs-starter-rest-api, pull requests merged in 2021-02, with the labels that each got.

#71 feat: acl base service, user acl service implementation
  src/shared/acl/acl-rule.constant.ts
  src/shared/acl/acl.service.spec.ts
  src/shared/acl/acl.service.ts
  src/shared/acl/action.constant.ts
  src/shared/acl/subject.constant.ts
  src/shared/constants/common.ts
  src/user/services/user-acl.service.spec.ts
  src/user/services/user-acl.service.ts
  src/user/user.module.ts
Labels: :technologist: Hackathon 2020

#80 feat: sonar analysis exclusion files
  sonar-project.properties
Labels: :technologist: Hackathon 2021 Q1

#83 feat: doc project struct
  README.md
  docs/project-structure.md
Labels: :technologist: Hackathon 2021 Q1

#84 fix: test folder exclusion
  sonar-project.properties
Labels: :technologist: Hackathon 2021 Q1

#64 feat: article entity
  migrations/1612590521475-CreateArticles.ts
  src/app.module.ts
  src/article/article.module.ts
  src/article/controllers/article.controller.spec.ts
  src/article/controllers/article.controller.ts
  src/article/dtos/article-input.dto.ts
  src/article/dtos/article-output.dto.ts
  src/article/dtos/author-output.dto.ts
  src/article/entities/article.entity.ts
  src/article/repositories/article.repository.spec.ts
  src/article/repositories/article.repository.ts
  src/article/services/article-acl.service.ts
  src/article/services/article.service.spec.ts
  src/article/services/article.service.ts
  src/user/entities/user.entity.ts
  src/user/repositories/user.repository.spec.ts
  src/user/services/user.service.spec.ts
Labels: :technologist: Hackathon 2020, :technologist: Hackathon 2021 Q1

#85 docs: middleware doc added
  docs/middleware.md
Labels: :technologist: Hackathon 2021 Q1

#86 Replace Pino with Winston Logger - Part 1/3
  README.md
  package-lock.json
  package.json
  src/cli.ts
  src/main.ts
  src/shared/interceptors/logging.interceptor.spec.ts
  src/shared/interceptors/logging.interceptor.ts
  src/shared/logger/logger.module.ts
  src/shared/logger/logger.service.spec.ts
  src/shared/logger/logger.service.ts
  src/shared/shared.module.ts
Labels: :pray: Please Review Me

#87 Replace Pino with Winston Logger - Part 2/3
  README.md
  src/app.controller.spec.ts
  src/app.controller.ts
  src/article/services/article.service.spec.ts
  src/shared/request-context/req-context.decorator.ts
  src/shared/request-context/request-context.dto.ts
Labels: :pray: Please Review Me
